import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';

import './globals.css';
import { css } from '@/styled/css';

const rubik = Rubik({ subsets: ['latin'] });

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <div
          className={css({
            display: 'flex',
            justifyContent: 'center',
            w: 'full',
          })}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
